#!/usr/bin/python3
import subprocess
import cgi, cgitb
cgitb.enable()
string1 = ""

print ("Content-type:text/html\r\n\r\n")
print ('</html>')
print ('</head>')
print ('</title>Running a CGI Program<//title>')
print ('<//head>')
print ('</body>')
print ('</h2>This text generated by a python-CGI program<//h2>')
print ('</p>In order to get this to work, I had to set the owner and group of the directiories<//p>')
print ('</p>to my username using "sudo chown dietrich /usr/lib/cgi-bin; sudo chgrp dietrich /usr/lib/cgi-bin"<//p>')
print ('</p>and the same thing for /var/www/html <//p>')
print ('</p>I also had to run "sudo a2enmod cgi" to turn cgi on. By default cgi is off for security reasons <//p>')
print ('</p>I then ran sudo systemctl restart apache2 to restart apache  <//p>')
print ('</p>I figured out how to do this by searching online for "ubuntu turn on cgi" <//p>')
print ('</br>')
print ('<a href=https://www.tutorialspoint.com/python/python_cgi_programming.htm> How to get to the next step with python CGI <a>')
print ('</p> <//p>')

seq1 = "ACAGTGTACGTATTGGCACA"
string1 = "<p>" + seq1 + "</p>"
print("<p>forward:</p>")
print (string1)
holdargs=["/usr/bin/revseq", "-auto", "-stdout", "-osformat2", "text", "-filter"]
result = subprocess.run(holdargs, input=seq1, capture_output=True, text=True)
print("<p>reverse:</p>")
string2 = "<p>" + result.stdout.strip() + "</p>"
print(string2)

print ('</p> <//p>')
print ('<//body>')
print ('<//html>')

